name: my_fatoorah
description: My Fatoorah Payment SDK Integration works for android and ios
version: 2.6.9
homepage: https://github.com/mo-ah-dawood/my_fatoorah

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
