name: my_fatoorah
description: My Fatoorah Payment SDK Integration
version: 0.0.1
author: Mohamed dawood <mo.ah.dawood@gmail.com>
homepage: https://github.com/mo-ah-dawood/my_fatoorah

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.dawood.my_fatoorah
    pluginClass: MyFatoorahPlugin
